version: '3'
services:
  app:
    restart: always
    image: "dyadik96/swagger:dev"
    expose:
      - 8000
      - 8001
    ports:
      - "8000:8000"
      - "8001:8001"
    links:
      - mongo
      - redis
    environment:
      - NODE_ENV=development
  mongo:
    image: "mongo:latest"
    expose:
      - '27017'
    restart: always
  redis:
    image: "redis:latest"
    restart: always